### ISSUE TITLE
I get this error please help out

### ISSUE THREAD

**Issue by vigneshgig** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#15]
Result saved in ./output
All Done, Bye Bye!
Traceback (most recent call last):
  File "/home/giuser/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/giuser/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/giuser/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [Unable to decode bytes as JPEG, PNG, GIF, or BMP]
	 [[{{node decode_image/cond_jpeg/else/_1/cond_png/else/_1/cond_gif/else/_1/Assert/Assert}}]]
	 [[input_reader/IteratorGetNext]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Stereo_Online_Adaptation.py", line 324, in <module>
    main(args)
  File "Stereo_Online_Adaptation.py", line 208, in main
    fetches = sess.run(tf_fetches)
  File "/home/giuser/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/giuser/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/giuser/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/giuser/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [Unable to decode bytes as JPEG, PNG, GIF, or BMP]
	 [[{{node decode_image/cond_jpeg/else/_1/cond_png/else/_1/cond_gif/else/_1/Assert/Assert}}]]
	 [[input_reader/IteratorGetNext]]

command used
python3 Stereo_Online_Adaptation.py     -l ./image_list.csv     -o ./output     --weights ./pretrained_nets/MADNet/kitti/weights.ckpt     --modelName MADNet     --blockConfig "block_config/MadNet_full.json"     --mode MAD     --sampleMode PROBABILITY

**Comment by AlessioTonioni** [comment]
Seems to be a problem with the images that you are trying to load. Either the paths in the csv are wrong, or the files are corrupted or they are not among the supported tensorflow format (JPEG, PNG, GIF, or BMP).

**Comment by vigneshgig** [comment]
thanks for reply ,Now I got it.
can you help out how to save disparity image map and depth image map while  testing a image.
The output folder does not contain depth image (predicted depth).
Thanks

**Comment by vigneshgig** [comment]
And can you explain the difference between the dispnet and madnet

**Comment by vigneshgig** [comment]
one more question how can i run the model without the ground truth image

**Comment by AlessioTonioni** [comment]
> thanks for reply ,Now I got it.
> can you help out how to save disparity image map and depth image map while testing a image.
> The output folder does not contain depth image (predicted depth).
> Thanks

The code only saves disparity maps, you can specify how frequently to save the outputs with the flag '--logDispStep'

> And can you explain the difference between the dispnet and madnet

Check the paper, they are two different architecture of neural networks

> one more question how can i run the model without the ground truth image

GT is only used to compute the error metrics so you can feed whatever image you want to the script, even a completely black one
