### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Inputs to operation validation_error/Select of type Select must have the same size and shape.  Input 0: [1,320,1216,3] != input 1: [1,320,1216,1]

### ISSUE THREAD

**Issue by siddhantbharti** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#26]
I am getting this error while running Stereo_Online_Adaptation.py. I would like to understand what is causing this to happen.
PS: My knowledge of tensorflow is limited.

**Comment by siddhantbharti** [comment]
Error changed to: Input 0: [1,320,1216,2] != input 1: [1,320,1216,1] - when I changed to images to greyscale.

**Comment by AlessioTonioni** [comment]
My guess is that you are using images with the wrong data format. Left and right frame should be 8 bit rgb images encoded as `png` or `jpg`. Ground truth images should be 8 or 16 bit 1 channel `png`. 
Without seeing the full error stack trace is hard to say what is going wrong.

**Comment by YJonmo** [comment]
Help please:

2019-11-08 11:25:25.390664: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:af:00.0
totalMemory: 15.90GiB freeMemory: 15.64GiB
2019-11-08 11:25:25.390696: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-11-08 11:25:25.924816: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-08 11:25:25.924846: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988] 0
2019-11-08 11:25:25.924855: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0: N
2019-11-08 11:25:25.925015: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15156 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:af:00.0, compute capability: 6.0)
Unable to restore any weight
Disparity Net Restored?: False from step 0
2019-11-08 11:25:29.661071: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2019-11-08 11:25:29.698288: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2019-11-08 11:25:30.046592: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2019-11-08 11:25:30.063236: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
All Done, Bye Bye!
Traceback (most recent call last):
File "/pkg/suse12/software/tensorflow/1.12.0-gpu-p100-foss-2018a-python-3.6.4/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
return fn(*args)
File "/pkg/suse12/software/tensorflow/1.12.0-gpu-p100-foss-2018a-python-3.6.4/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
options, feed_dict, fetch_list, target_list, run_metadata)
File "/pkg/suse12/software/tensorflow/1.12.0-gpu-p100-foss-2018a-python-3.6.4/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Need minval < maxval, got 0 >= -1
[[{{node random_uniform}} = RandomUniformInt[T=DT_INT32, Tout=DT_INT32, seed=0, seed2=0](random_uniform/shape, random_uniform/min, sub_1)]]
[[{{node input_reader/training_set_reader/IteratorGetNext}} = IteratorGetNextoutput_shapes=[[4,256,256,3], [4,256,256,3], [4,256,256,1]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"]]
[[{{node input_reader/training_set_reader/IteratorGetNext/_23}} = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_108_input_reader/training_set_reader/IteratorGetNext", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "Train.py", line 189, in
main(args)
File "Train.py", line 141, in main
fetches = sess.run(tf_fetches,options=run_options)
File "/pkg/suse12/software/tensorflow/1.12.0-gpu-p100-foss-2018a-python-3.6.4/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
run_metadata_ptr)
File "/pkg/suse12/software/tensorflow/1.12.0-gpu-p100-foss-2018a-python-3.6.4/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
feed_dict_tensor, options, run_metadata)
File "/pkg/suse12/software/tensorflow/1.12.0-gpu-p100-foss-2018a-python-3.6.4/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
run_metadata)
File "/pkg/suse12/software/tensorflow/1.12.0-gpu-p100-foss-2018a-python-3.6.4/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Need minval < maxval, got 0 >= -1
[[{{node random_uniform}} = RandomUniformInt[T=DT_INT32, Tout=DT_INT32, seed=0, seed2=0](random_uniform/shape, random_uniform/min, sub_1)]]
[[node input_reader/training_set_reader/IteratorGetNext (defined at /home/jonmoham/Python/Real_timeStereo/Data_utils/data_reader.py:179) = IteratorGetNextoutput_shapes=[[4,256,256,3], [4,256,256,3], [4,256,256,1]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"]]
[[{{node input_reader/training_set_reader/IteratorGetNext/_23}} = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_108_input_reader/training_set_reader/IteratorGetNext", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]]

**Comment by YJonmo** [comment]
it looks like it is something to do with the dimension of the image. The --imageShape should be smaller the actual size of the image.

**Comment by AlessioTonioni** [comment]
I think that you are trying to extract a crop bigger than the size of the image.

**Comment by AlessioTonioni** [comment]
Should be fixed here:
https://github.com/CVLAB-Unibo/Real-time-self-adaptive-deep-stereo/commit/20add4c4ef087dd551b9de776a6d58a474a44d77

**Comment by jameszhou12138** [comment]
Hi,
I have the same problem. I changed the `--imageShape` according to my image, but it doesn't work.
And the full errors are showed as follows:
```
2023-12-20 16:45:25.546044: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Disparity Net Restored?: True, number of restored variables: 98
Stereo_Online_Adaptation.py:265: RuntimeWarning: invalid value encountered in double_scalars
  f_out.write('EPE,{},{}\n'.format(epe_accumulator,epe_accumulator/step))
Stereo_Online_Adaptation.py:266: RuntimeWarning: invalid value encountered in double_scalars
  f_out.write('bad3,{},{}\n'.format(bad3_accumulator,bad3_accumulator/step))
Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/py3_6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/xxx/anaconda3/envs/py3_6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/xxx/anaconda3/envs/py3_6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Inputs to operation validation_error/Select of type Select must have the same size and shape.  Input 0: [1,800,928,3] != input 1: [1,800,928,1]
         [[{{node validation_error/Select}} = Select[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](validation_error/Equal, reprojection_3/image_sampling/Reshape_2, validation_error/ones_like_1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Stereo_Online_Adaptation.py", line 208, in main
    fetches = sess.run(tf_fetches)
  File "/home/xxx/anaconda3/envs/py3_6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/xxx/anaconda3/envs/py3_6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/xxx/anaconda3/envs/py3_6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/xxx/anaconda3/envs/py3_6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Inputs to operation validation_error/Select of type Select must have the same size and shape.  Input 0: [1,800,928,3] != input 1: [1,800,928,1]
         [[node validation_error/Select (defined at Stereo_Online_Adaptation.py:77)  = Select[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](validation_error/Equal, reprojection_3/image_sampling/Reshape_2, validation_error/ones_like_1)]]

Caused by op 'validation_error/Select', defined at:
  File "Stereo_Online_Adaptation.py", line 325, in <module>
    main(args)
  File "Stereo_Online_Adaptation.py", line 77, in main
    valid_map = tf.where(tf.equal(gt_image_batch, 0), tf.zeros_like(gt_image_batch, dtype=tf.float32), tf.ones_like(gt_image_batch, dtype=tf.float32))
  File "/home/xxx/anaconda3/envs/py3_6/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 2624, in where
    return gen_math_ops.select(condition=condition, x=x, y=y, name=name)
  File "/home/xxx/anaconda3/envs/py3_6/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 6997, in select
    "Select", condition=condition, t=x, e=y, name=name)
  File "/home/xxx/anaconda3/envs/py3_6/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/xxx/anaconda3/envs/py3_6/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/xxx/anaconda3/envs/py3_6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/xxx/anaconda3/envs/py3_6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Inputs to operation validation_error/Select of type Select must have the same size and shape.  Input 0: [1,800,928,3] != input 1: [1,800,928,1]
         [[node validation_error/Select (defined at Stereo_Online_Adaptation.py:77)  = Select[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](validation_error/Equal, reprojection_3/image_sampling/Reshape_2, validation_error/ones_like_1)]]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Stereo_Online_Adaptation.py", line 325, in <module>
    main(args)
  File "Stereo_Online_Adaptation.py", line 267, in main
    f_out.write('time,{},{}\n'.format(exec_time,exec_time/step))
ZeroDivisionError: division by zero
```

Thanks.
